// Cars models
export const CAR_ID_TO_CAR_MANUFACTURER: Record<number, { name: string; manufacturer: string }> = {
  1: { name: 'Skip Barber Formula 2000', manufacturer: 'skipbarber' },
  2: { name: 'Modified - SK', manufacturer: 'unknown' },
  3: { name: 'Pontiac Solstice', manufacturer: 'pontiac' },
  4: { name: '[Legacy] Pro Mazda', manufacturer: 'unknown' },
  5: { name: "Legends Ford '34 Coupe", manufacturer: 'unknown' },
  10: { name: 'Pontiac Solstice - Rookie', manufacturer: 'pontiac' },
  11: { name: "[Retired] Legends Ford '34 Coupe - Rookie", manufacturer: 'unknown' },
  12: { name: '[Retired] Chevrolet Monte Carlo SS', manufacturer: 'chevrolet' },
  13: { name: 'Radical SR8', manufacturer: 'radical' },
  18: { name: 'Silver Crown', manufacturer: 'unknown' },
  20: { name: '[Legacy] NASCAR Truck Chevrolet Silverado - 2008', manufacturer: 'chevrolet' },
  21: { name: '[Legacy] Riley MkXX Daytona Prototype - 2008', manufacturer: 'riley' },
  22: { name: '[Legacy] NASCAR Cup Chevrolet Impala COT - 2009', manufacturer: 'chevrolet' },
  23: { name: 'SCCA Spec Racer Ford', manufacturer: 'scca' },
  24: { name: '[Legacy] ARCA Menards Chevrolet Impala', manufacturer: 'chevrolet' },
  25: { name: 'Lotus 79', manufacturer: 'lotus' },
  26: { name: 'Chevrolet Corvette C6.R GT1', manufacturer: 'chevrolet' },
  27: { name: 'VW Jetta TDI Cup', manufacturer: 'vw' },
  28: { name: '[Legacy] V8 Supercar Ford Falcon - 2009', manufacturer: 'ford' },
  29: { name: '[Legacy] Dallara IR-05', manufacturer: 'dallara' },
  30: { name: 'Ford Mustang FR500S', manufacturer: 'ford' },
  31: { name: 'Modified - NASCAR Whelen Tour', manufacturer: 'unknown' },
  33: { name: 'Williams-Toyota FW31', manufacturer: 'williams' },
  34: { name: '[Legacy] Mazda MX-5 Cup - 2010', manufacturer: 'mazda' },
  35: { name: '[Legacy] Mazda MX-5 Roadster - 2010', manufacturer: 'mazda' },
  36: { name: 'Street Stock - Panther C1', manufacturer: 'unknown' },
  37: { name: 'Sprint Car', manufacturer: 'unknown' },
  38: { name: '[Legacy] NASCAR Nationwide Chevrolet Impala - 2012', manufacturer: 'chevrolet' },
  39: { name: 'HPD ARX-01c', manufacturer: 'hpd' },
  40: { name: 'Ford GT GT2', manufacturer: 'ford' },
  41: { name: 'Cadillac CTS-V Racecar', manufacturer: 'cadillac' },
  42: { name: 'Lotus 49', manufacturer: 'lotus' },
  43: { name: '[Legacy] McLaren MP4-12C GT3', manufacturer: 'mclaren' },
  44: { name: 'Kia Optima', manufacturer: 'kia' },
  45: { name: '[Legacy] NASCAR Cup Chevrolet SS - 2013', manufacturer: 'chevrolet' },
  46: { name: '[Legacy] NASCAR Cup Ford Fusion - 2016', manufacturer: 'ford' },
  48: { name: 'Ruf RT 12R AWD', manufacturer: 'ruf' },
  49: { name: 'Ruf RT 12R RWD', manufacturer: 'ruf' },
  50: { name: 'Ruf RT 12R Track', manufacturer: 'ruf' },
  51: { name: '[Legacy] NASCAR Xfinity Ford Mustang - 2016', manufacturer: 'ford' },
  52: { name: 'Ruf RT 12R C-Spec', manufacturer: 'ruf' },
  54: { name: 'Super Late Model', manufacturer: 'unknown' },
  55: { name: '[Legacy] BMW Z4 GT3', manufacturer: 'bmw' },
  56: { name: 'NASCAR Cup Series Toyota Camry', manufacturer: 'toyota' },
  57: { name: '[Legacy] Dallara DW12', manufacturer: 'dallara' },
  58: { name: '[Legacy] NASCAR Xfinity Chevrolet Camaro - 2014', manufacturer: 'chevrolet' },
  59: { name: 'Ford GT GT3', manufacturer: 'ford' },
  60: { name: '[Legacy] V8 Supercar Holden VF Commodore - 2014', manufacturer: 'holden' },
  61: { name: '[Legacy] V8 Supercar Ford FG Falcon - 2014', manufacturer: 'ford' },
  62: { name: '[Retired] NASCAR Gander Outdoors Toyota Tundra', manufacturer: 'toyota' },
  63: { name: '[Retired] NASCAR Trucks Series Chevrolet Silverado - 2018', manufacturer: 'chevrolet' },
  64: { name: 'Aston Martin DBR9 GT1', manufacturer: 'aston' },
  67: { name: 'Global Mazda MX-5 Cup', manufacturer: 'mazda' },
  69: { name: '[Legacy] NASCAR Xfinity Toyota Camry - 2015', manufacturer: 'toyota' },
  70: { name: 'Chevrolet Corvette C7 Daytona Prototype', manufacturer: 'chevrolet' },
  71: { name: 'McLaren MP4-30', manufacturer: 'mclaren' },
  72: { name: '[Legacy] Mercedes-AMG GT3', manufacturer: 'mercedes' },
  73: { name: '[Legacy] Audi R8 LMS GT3', manufacturer: 'audi' },
  74: { name: 'Formula Renault 2.0', manufacturer: 'renault' },
  76: { name: 'Audi 90 GTO', manufacturer: 'audi' },
  77: { name: 'Nissan GTP ZX-T', manufacturer: 'nissan' },
  78: { name: 'Dirt Late Model - Limited', manufacturer: 'unknown' },
  79: { name: 'Dirt Street Stock', manufacturer: 'unknown' },
  80: { name: 'Dirt Sprint Car - 305', manufacturer: 'unknown' },
  81: { name: 'Ford Fiesta RS WRC', manufacturer: 'ford' },
  82: { name: "Dirt Legends Ford '34 Coupe", manufacturer: 'unknown' },
  83: { name: 'Dirt Late Model - Pro', manufacturer: 'unknown' },
  84: { name: 'Dirt Late Model - Super', manufacturer: 'unknown' },
  85: { name: 'Dirt Sprint Car - 360', manufacturer: 'unknown' },
  86: { name: 'Dirt Sprint Car - 410', manufacturer: 'unknown' },
  87: { name: 'Dirt Sprint Car - 360 Non-Winged', manufacturer: 'unknown' },
  88: { name: '[Legacy] Porsche 911 GT3 Cup (991)', manufacturer: 'porsche' },
  89: { name: 'Dirt Sprint Car - 410 Non-Winged', manufacturer: 'unknown' },
  91: { name: 'VW Beetle', manufacturer: 'vw' },
  92: { name: 'Ford GTE', manufacturer: 'ford' },
  93: { name: 'Ferrari 488 GTE', manufacturer: 'ferrari' },
  94: { name: '[Legacy] Ferrari 488 GT3', manufacturer: 'ferrari' },
  95: { name: 'Dirt UMP Modified', manufacturer: 'unknown' },
  96: { name: 'Dirt Midget', manufacturer: 'unknown' },
  98: { name: 'Audi R18', manufacturer: 'audi' },
  99: { name: 'Dallara IR18', manufacturer: 'dallara' },
  100: { name: 'Porsche 919', manufacturer: 'porsche' },
  101: { name: 'Subaru WRX STI', manufacturer: 'subaru' },
  102: { name: 'Porsche 911 RSR', manufacturer: 'porsche' },
  103: { name: 'NASCAR Cup Series Chevrolet Camaro ZL1', manufacturer: 'chevrolet' },
  104: { name: 'Lucas Oil Off Road Pro 2 Truck', manufacturer: 'unknown' },
  105: { name: 'Formula Renault 3.5', manufacturer: 'renault' },
  106: { name: 'Dallara F3', manufacturer: 'dallara' },
  107: { name: 'Lucas Oil Off Road Pro 4 Truck', manufacturer: 'unknown' },
  109: { name: 'BMW M8 GTE', manufacturer: 'bmw' },
  110: { name: 'NASCAR Cup Series Ford Mustang', manufacturer: 'ford' },
  111: { name: 'NASCAR Truck Chevrolet Silverado', manufacturer: 'chevrolet' },
  112: { name: 'Audi RS 3 LMS TCR', manufacturer: 'audi' },
  113: { name: 'Lucas Oil Off Road Pro 2 Lite', manufacturer: 'unknown' },
  114: { name: 'NASCAR XFINITY Chevrolet Camaro', manufacturer: 'chevrolet' },
  115: { name: 'NASCAR XFINITY Ford Mustang', manufacturer: 'ford' },
  116: { name: 'NASCAR XFINITY Toyota Supra', manufacturer: 'toyota' },
  117: { name: '[Legacy] Supercars Holden ZB Commodore', manufacturer: 'holden' },
  118: { name: '[Legacy] Supercars Ford Mustang GT', manufacturer: 'ford' },
  119: { name: 'Porsche 718 Cayman GT4 Clubsport MR', manufacturer: 'porsche' },
  120: { name: 'Indy Pro 2000 PM-18', manufacturer: 'unknown' },
  121: { name: 'USF 2000', manufacturer: 'unknown' },
  122: { name: 'BMW M4 F82 GT4 - 2018', manufacturer: 'bmw' },
  123: { name: 'NASCAR Truck Ford F150', manufacturer: 'ford' },
  124: { name: 'NASCAR Legends Chevrolet Monte Carlo - 1987', manufacturer: 'chevrolet' },
  125: { name: 'NASCAR Legends Ford Thunderbird - 1987', manufacturer: 'ford' },
  127: { name: 'Chevrolet Corvette C8.R GTE', manufacturer: 'chevrolet' },
  128: { name: 'Dallara P217', manufacturer: 'dallara' },
  129: { name: 'Dallara iR-01', manufacturer: 'dallara' },
  131: { name: 'Dirt Big Block Modified', manufacturer: 'unknown' },
  132: { name: 'BMW M4 GT3 EVO', manufacturer: 'bmw' },
  133: { name: 'Lamborghini Huracán GT3 EVO', manufacturer: 'lamborghini' },
  134: { name: 'Dirt 358 Modified', manufacturer: 'unknown' },
  135: { name: 'McLaren 570S GT4', manufacturer: 'mclaren' },
  137: { name: '[Legacy] Porsche 911 GT3 R', manufacturer: 'porsche' },
  138: { name: 'VW Beetle - Lite', manufacturer: 'vw' },
  139: { name: 'NASCAR Cup Series Next Gen Chevrolet Camaro ZL1', manufacturer: 'chevrolet' },
  140: { name: 'NASCAR Cup Series Next Gen Ford Mustang', manufacturer: 'ford' },
  141: { name: 'NASCAR Cup Series Next Gen Toyota Camry', manufacturer: 'toyota' },
  142: { name: 'Formula Vee', manufacturer: 'unknown' },
  143: { name: '[Legacy] Porsche 911 GT3 Cup (992.1)', manufacturer: 'porsche' },
  144: { name: 'Ferrari 488 GT3 Evo 2020', manufacturer: 'ferrari' },
  145: { name: 'Mercedes-AMG W12 E Performance', manufacturer: 'mercedes' },
  146: { name: 'Hyundai Elantra N TCR', manufacturer: 'hyundai' },
  147: { name: 'Honda Civic Type R TCR', manufacturer: 'honda' },
  148: { name: 'FIA F4', manufacturer: 'unknown' },
  149: { name: 'Radical SR10', manufacturer: 'radical' },
  150: { name: 'Aston Martin Vantage GT4', manufacturer: 'aston' },
  151: { name: 'Stock Car Brasil Chevrolet Cruze', manufacturer: 'chevrolet' },
  152: { name: 'Stock Car Brasil Toyota Corolla', manufacturer: 'toyota' },
  153: { name: 'Hyundai Veloster N TCR', manufacturer: 'hyundai' },
  154: { name: 'NASCAR Legends Buick LeSabre - 1987', manufacturer: 'buick' },
  155: { name: 'NASCAR Truck Toyota Tundra TRD Pro', manufacturer: 'toyota' },
  156: { name: 'Mercedes-AMG GT3 2020', manufacturer: 'mercedes' },
  157: { name: 'Mercedes-AMG GT4', manufacturer: 'mercedes' },
  158: { name: 'Porsche Mission R', manufacturer: 'porsche' },
  159: { name: 'BMW M Hybrid V8', manufacturer: 'bmw' },
  160: { name: 'Toyota GR86', manufacturer: 'toyota' },
  161: { name: 'Mercedes-AMG W13 E Performance', manufacturer: 'mercedes' },
  162: { name: 'Renault Clio', manufacturer: 'renault' },
  163: { name: 'Ray FF1600', manufacturer: 'unknown' },
  164: { name: 'Late Model Stock', manufacturer: 'unknown' },
  165: { name: 'Ligier JS P320', manufacturer: 'ligier' },
  167: { name: '[Legacy] Gen 4 Cup', manufacturer: 'chevrolet' },
  168: { name: 'Cadillac V-Series.R GTP', manufacturer: 'cadillac' },
  169: { name: 'Porsche 911 GT3 R (992)', manufacturer: 'porsche' },
  170: { name: 'Acura ARX-06 GTP', manufacturer: 'acura' },
  171: { name: 'Super Formula SF23 - Toyota', manufacturer: 'superformula' },
  172: { name: 'Super Formula SF23 - Honda', manufacturer: 'superformula' },
  173: { name: 'Ferrari 296 GT3', manufacturer: 'ferrari' },
  174: { name: 'Porsche 963 GTP', manufacturer: 'porsche' },
  175: { name: 'NASCAR Legends Pontiac Grand Prix - 1987', manufacturer: 'pontiac' },
  176: { name: 'Audi R8 LMS EVO II GT3', manufacturer: 'audi' },
  178: { name: 'Super Formula Lights', manufacturer: 'superformula' },
  179: { name: 'SRX', manufacturer: 'srx' },
  180: { name: 'Dirt Micro Sprint Car - Winged', manufacturer: 'unknown' },
  181: { name: 'Dirt Micro Sprint Car - Non-Winged', manufacturer: 'unknown' },
  182: { name: 'Dirt Outlaw Micro Sprint Car - Winged', manufacturer: 'unknown' },
  183: { name: 'Dirt Outlaw Micro Sprint Car - Non-Winged', manufacturer: 'unknown' },
  184: { name: 'Chevrolet Corvette Z06 GT3.R', manufacturer: 'chevrolet' },
  185: { name: 'Ford Mustang GT3', manufacturer: 'ford' },
  186: { name: 'Street Stock - Casino M2', manufacturer: 'unknown' },
  187: { name: 'Street Stock - Eagle T3', manufacturer: 'unknown' },
  188: { name: 'McLaren 720S GT3 EVO', manufacturer: 'mclaren' },
  189: { name: 'BMW M4 G82 GT4 Evo', manufacturer: 'bmw' },
  190: { name: 'Supercars Ford Mustang Gen 3', manufacturer: 'ford' },
  191: { name: 'Mini Stock', manufacturer: 'unknown' },
  192: { name: 'Supercars Chevrolet Camaro Gen 3', manufacturer: 'chevrolet' },
  193: { name: 'Dirt Mini Stock', manufacturer: 'unknown' },
  194: { name: 'Acura NSX GT3 EVO 22', manufacturer: 'acura' },
  195: { name: 'BMW M2 CS Racing', manufacturer: 'bmw' },
  196: { name: 'Ferrari 499P', manufacturer: 'ferrari' },
  198: { name: 'ARCA Chevrolet SS', manufacturer: 'chevrolet' },
  199: { name: 'ARCA Ford Mustang', manufacturer: 'ford' },
  200: { name: 'ARCA Toyota Camry', manufacturer: 'toyota' },
  201: { name: 'Gen 4 Chevrolet Monte Carlo - 2003', manufacturer: 'chevrolet' },
  202: { name: 'Gen 4 Ford Taurus - 2003', manufacturer: 'ford' },
  203: { name: 'Ferrari 296 Challenge', manufacturer: 'ferrari' },
  204: { name: 'Ford Mustang GT4', manufacturer: 'ford' },
  205: { name: 'Dallara IL-15', manufacturer: 'dallara' },
  206: { name: 'Aston Martin Vantage GT3 EVO', manufacturer: 'aston' },
  207: { name: 'FIA Cross Car', manufacturer: 'unknown' },
  208: { name: 'Porsche 911 Cup (992.2)', manufacturer: 'porsche' },
};