export const seriesMapping: Record<string, string> = {
  "32": "Legends Cup by Go Motorsports Shop",
  "33": "CARS Late Model Stock Series",
  "53": "Silver Crown Cup",
  "62": "NASCAR iRacing Class B Series",
  "65": "Lotus 79 Grand Prix Series",
  "74": "Radical Esports Cup",
  "103": "NASCAR Xfinity Series - Fixed",
  "112": "Production Car Challenge by Sim-Lab",
  "131": "Sprint Car Cup",
  "132": "INDYCAR Series - Oval - Fixed",
  "133": "INDYCAR Series",
  "139": "Global Mazda MX-5 Cup by Fanatec",
  "164": "NASCAR Class C Series - Fixed",
  "165": "INDYCAR Series - Fixed",
  "182": "Rookie Street Stock Series by Fanatec",
  "190": "Street Stock Series by Next Level Racing",
  "201": "Lotus 49 Grand Prix Legends",
  "210": "Global Sports Car Challenge by Fanatec",
  "223": "Super Late Model Series",
  "228": "GT Sprint Series by Simucube",
  "231": "Advanced Mazda MX-5 Cup by Heusinkveld",
  "237": "GT Endurance Series by Simucube",
  "259": "NASCAR Pickup Cup",
  "260": "Formula A - Cosworth Cup Grand Prix",
  "275": "Nurburgring Endurance Championship",
  "285": "IMSA Vintage Series",
  "299": "iRacing Porsche Cup by CONSPIT",
  "305": "DIRTcar 360 Sprint Car Series",
  "308": "World of Outlaws Late Model Series",
  "315": "Dirt Legends Cup",
  "325": "Rallycross Series by Trak Racer",
  "331": "Global Endurance Tour",
  "353": "Ferrari 296 Challenge",
  "369": "World of Outlaws Late Model Series - Fixed",
  "416": "Super Late Model Series - Fixed",
  "419": "IMSA Endurance Series",
  "430": "TCR Virtual Challenge - Fixed",
  "431": "Formula C -  Dallara F3 Series",
  "432": "Proto-GT Challenge",
  "440": "CARS Late Model Stock Series - Fixed",
  "442": "DIRTcar UMP Modified Series - Fixed",
  "446": "DIRTcar Street Stock Rookie Racing Series",
  "451": "Creventic Endurance Series",
  "455": "Formula Vee Series by trophi.ai",
  "456": "Formula C - Dallara F3 Series - Fixed",
  "457": "Prototype  Challenge – Fixed",
  "459": "VW Lite iRX Rookie Series by Trak Racer",
  "460": "iRX Volkswagen Beetle Lite Series by Trak Racer",
  "461": "Rallycross Series - Fixed by Trak Racer",
  "462": "Pro 2 Lite Off-Road Rookie Series by Trak Racer",
  "463": "Pro 4 Off-Road Series - Fixed by Trak Racer",
  "464": "Pro 2 Off-Road Series - Fixed by Trak Racer",
  "466": "DIRTcar 358 Modified Series",
  "471": "Dallara DW12 Dash",
  "476": "iRacing Porsche Cup - Fixed by CONSPIT",
  "483": "Rookie Legends Cup by Simshop",
  "484": "Formula A - Cosworth Cup Grand Prix - Fixed",
  "495": "Formula A - Grand Prix Tour",
  "496": "Formula A - Grand Prix Tour - Fixed",
  "498": "FIA Formula 4 Challenge - Fixed",
  "500": "Dirt Super Late Model Tour",
  "501": "Dirt 410 Sprint Car Tour",
  "502": "Sports Car Challenge by Falken Tyre",
  "503": "TCR Virtual Challenge",
  "514": "Toyota GR86 Cup by SIMAGIC",
  "515": "DIRTcar 360 Sprint Car Series - Fixed",
  "519": "Renault Clio Cup",
  "520": "Formula 1600 Rookie Series",
  "521": "Motorsport UK FF 1600 Trophy by Thrustmaster",
  "524": "NASCAR Gen 4 Cup Series",
  "525": "LMP3 Trophy",
  "526": "Ring Meister",
  "530": "Ford Mustang Challenge by Skip Barber",
  "535": "GTE Sprint Series",
  "536": "Formula B - Super Formula Series",
  "537": "Formula B - Super Formula Series - Fixed",
  "538": "Draft Master Challenge by Simagic",
  "539": "IMSA iRacing Series - Fixed",
  "540": "FIA F4 Esports Regional Tour - Asia Pacific",
  "541": "FIA F4 Esports Regional Tour - America",
  "542": "FIA F4 Esports Regional Tour - Europe",
  "550": "Micro Winged Sprint Car Rookie by Thrustmaster",
  "551": "Formula C - Super Formula Lights by Ready Set Sim",
  "552": "Formula C - Super Formula Lights - Fixed by Ready Set Sim",
  "553": "Outlaw Micro Showdown",
  "554": "SRX Series - Fixed",
  "557": "BMW M Power Challenge",
  "558": "Micro Non Wing Sprint Car Rookie Series",
  "559": "Rain Master Challenge",
  "560": "INDY NXT Thrustmaster Qualifying Series",
  "562": "Legends Road Cup by Go Motorsports Shop",
  "563": "Jr Open Wheel Oval Challenge",
  "564": "Mini Stock Rookie Series by Thrustmaster",
  "567": "Dirt Mini Stock Rookie Series",
  "570": "World of Outlaws Pro Qualifying Series",
  "571": "BMW M2 Cup by Nitro Concepts",
  "572": "IMSA Sportscar Endurance Challenge",
  "574": "Super Late Model Tour",
  "575": "NASCAR Modified Tour",
  "576": "DIRTcar UMP Modified Series",
  "579": "Vintage Grand Prix Tour",
  "584": "Production Endurance Challenge",
  "588": "Advanced Pro2 Lite Off Road Series by Trak Racer",
  "591": "LMP2 Challenge - Fixed",
  "592": "Indy NXT Road Series - Fixed",
  "593": "Indy NXT Oval Series - Fixed",
  "594": "iRacing GT3 Regional Tour - Asia Pacific",
  "595": "iRacing GT3 Regional Tour - Americas",
  "596": "iRacing GT3 Regional Tour - Europe",
  "597": "Suzuka 1000km"
}
