export const SPRITE_SIZE = 64;
export const SPRITES_PER_ROW = 7;
export const SPRITES_PER_COLUMN = 6;

export const CAR_MANUFACTURER_SPRITE_POSITIONS: Record<
  string,
  { x: number; y: number }
> = {
  acura: { x: 1, y: 0 },
  astonmartin: { x: 2, y: 0 },
  audi: { x: 3, y: 0 },
  bmw: { x: 4, y: 0 },
  bmwm: { x: 5, y: 0 },
  buick: { x: 6, y: 0 },
  cadillac: { x: 0, y: 1 },
  caterham: { x: 1, y: 1 },
  chevrolet: { x: 2, y: 1 },
  dallara: { x: 3, y: 1 },
  dodgeram: { x: 4, y: 1 },
  ferrari: { x: 5, y: 1 },
  fia: { x: 6, y: 1 },
  ford: { x: 0, y: 2 },
  holden: { x: 1, y: 2 },
  honda: { x: 2, y: 2 },
  hpd: { x: 3, y: 2 },
  hyundai: { x: 4, y: 2 },
  iracing: { x: 5, y: 2 },
  kia: { x: 6, y: 2 },
  lamborghini: { x: 0, y: 3 },
  ligier: { x: 1, y: 3 },
  lotus: { x: 2, y: 3 },
  mazda: { x: 3, y: 3 },
  mclaren: { x: 4, y: 3 },
  mercedes: { x: 5, y: 3 },
  nissan: { x: 6, y: 3 },
  pontiac: { x: 0, y: 4 },
  porsche: { x: 1, y: 4 },
  radical: { x: 2, y: 4 },
  renault: { x: 3, y: 4 },
  riley: { x: 4, y: 4 },
  ruf: { x: 5, y: 4 },
  scca: { x: 6, y: 4 },
  skipbarber: { x: 0, y: 5 },
  srx: { x: 1, y: 5 },
  subaru: { x: 2, y: 5 },
  toyota: { x: 3, y: 5 },
  unknown: { x: 0, y: 0 },
  vw: { x: 4, y: 5 },
  williams: { x: 5, y: 5 },
};
