import { readFileSync, writeFileSync, mkdirSync } from 'fs';
import path from 'path';

/**
 * Builds the iRacing -> Garage 61 id lookup from Garage 61's own catalogue
 * exports.
 *
 * Garage 61 numbers tracks and cars in its own id space, unrelated to
 * iRacing's, so a lap-search URL cannot be built from session data alone. Both
 * exports carry the iRacing id alongside their own as `platform_id`, which is
 * the only thing that ties the two together.
 *
 * Ids only, deliberately. Names would be five times the bytes for something
 * the session already tells us, and nothing reads them.
 *
 * Regenerate with: npm run generate-garage61-ids -- <directory of the CSVs>
 */

const OUTPUT_FILE = './src/app/garage61/_GENERATED_ids.ts';

interface CatalogueRow {
  /** Garage 61's own id. */
  id: number;
  /** The matching iRacing id, from the same row's `platform_id`. */
  platformId: number;
}

/**
 * Minimal CSV reader for these two files: a header row, comma separators, no
 * quoted fields in the columns we read. Only `id`, `platform` and
 * `platform_id` are used, so a name containing a comma cannot break the
 * columns we care about as long as it is not one of them.
 */
const readCatalogue = (file: string): CatalogueRow[] => {
  const lines = readFileSync(file, 'utf8').split(/\r?\n/).filter(Boolean);
  if (lines.length < 2) throw new Error(`${file} has no rows`);

  const header = lines[0].split(',');
  const idCol = header.indexOf('id');
  const platformCol = header.indexOf('platform');
  const platformIdCol = header.indexOf('platform_id');
  if (idCol < 0 || platformCol < 0 || platformIdCol < 0) {
    throw new Error(`${file} is missing id/platform/platform_id columns`);
  }

  const rows: CatalogueRow[] = [];
  for (const line of lines.slice(1)) {
    const cells = line.split(',');
    // Other sims share the export; only iRacing ids mean anything here.
    if (cells[platformCol] !== 'iracing') continue;
    const id = Number(cells[idCol]);
    const platformId = Number(cells[platformIdCol]);
    if (!Number.isInteger(id) || !Number.isInteger(platformId)) continue;
    if (id <= 0 || platformId <= 0) continue;
    rows.push({ id, platformId });
  }
  return rows;
};

/**
 * One `iRacing id: Garage 61 id` map, sorted by key so a regenerated file
 * diffs as the rows that actually changed.
 *
 * A duplicated iRacing id would mean two Garage 61 entries claim the same
 * car or track, which silently picks a winner; that is worth failing on rather
 * than shipping a lookup that is wrong for one of them.
 */
const toMapLiteral = (rows: CatalogueRow[], what: string): string => {
  const byPlatformId = new Map<number, number>();
  for (const row of rows) {
    const existing = byPlatformId.get(row.platformId);
    if (existing !== undefined && existing !== row.id) {
      throw new Error(
        `Two Garage 61 ${what} ids (${existing}, ${row.id}) claim iRacing id ${row.platformId}`
      );
    }
    byPlatformId.set(row.platformId, row.id);
  }

  const entries = [...byPlatformId.entries()].sort((a, b) => a[0] - b[0]);
  // Wrapped at a fixed count per line rather than one per line: 670 entries
  // one to a line is a lot of file for what is really a table.
  const perLine = 8;
  const lines: string[] = [];
  for (let i = 0; i < entries.length; i += perLine) {
    lines.push(
      '  ' +
        entries
          .slice(i, i + perLine)
          .map(([platformId, id]) => `${platformId}: ${id},`)
          .join(' ')
    );
  }
  return lines.join('\n');
};

export const generateGarage61Ids = (sourceDir: string) => {
  const tracks = readCatalogue(path.join(sourceDir, 'garage61_tracks.csv'));
  const cars = readCatalogue(path.join(sourceDir, 'garage61_cars.csv'));

  const content = `// This file is auto-generated by tools/generate-garage61-ids.ts
// Do not edit manually - run: npm run generate-garage61-ids -- <csv directory>

/**
 * iRacing id -> Garage 61 id, for tracks and cars.
 *
 * Garage 61 numbers everything in its own id space, so a lap-search URL cannot
 * be built from what iRacing reports without this table. The mapping is layout
 * exact: iRacing gives every track configuration its own id, and Garage 61
 * lists them separately too, so Algarve Grand Prix, Grand Prix with chicanes
 * and Moto each resolve to a different Garage 61 track.
 *
 * A track or car newer than this snapshot is simply absent; callers must
 * handle a missing id rather than assume one.
 */

/** iRacing \`WeekendInfo.TrackID\` -> Garage 61 track id. */
export const GARAGE61_TRACK_IDS: Readonly<Record<number, number>> = {
${toMapLiteral(tracks, 'track')}
};

/** iRacing \`DriverInfo.Drivers[].CarID\` -> Garage 61 car id. */
export const GARAGE61_CAR_IDS: Readonly<Record<number, number>> = {
${toMapLiteral(cars, 'car')}
};
`;

  mkdirSync(path.dirname(OUTPUT_FILE), { recursive: true });
  writeFileSync(OUTPUT_FILE, content, 'utf8');
  console.log(
    `Generated Garage 61 ids: ${tracks.length} tracks, ${cars.length} cars`
  );
};

const sourceDir = process.argv[2];
if (!sourceDir) {
  console.error(
    'Usage: npm run generate-garage61-ids -- <directory containing garage61_tracks.csv and garage61_cars.csv>'
  );
  process.exit(1);
}
generateGarage61Ids(sourceDir);
