import { readFileSync, writeFileSync } from 'fs';

interface Series {
  series_id: number;
  series_name: string;
}

export const generateSeriesMapping = () => {
  const seriesData = readFileSync('./asset-data/series.json', 'utf8');
  const series: Series[] = JSON.parse(seriesData);

  const mapping = series.reduce(
    (acc, s) => {
      acc[String(s.series_id)] = s.series_name;
      return acc;
    },
    {} as Record<string, string>
  );

  const sortedEntries = Object.entries(mapping).sort((a, b) => {
    return parseInt(a[0]) - parseInt(b[0]);
  });

  const content = `// This file is auto-generated by tools/generate-series-mapping.ts
// Do not edit manually - run generate-assets via tools/index.ts to regenerate

export const seriesMapping: Record<string, string> = {
${sortedEntries.map(([id, name]) => `  "${id}": "${name.replace(/"/g, '\\"')}"`).join(',\n')}
}
`;

  writeFileSync('./src/frontend/utils/seriesMapping.ts', content, 'utf8');
  console.log(`Generated series mapping with ${sortedEntries.length} entries`);
};

